### PR TITLE
FlintstoneDB::getAll() method added

### PR DESCRIPTION
**Pull request by urmaul**
I think this is a required method. Right now to do this we have to walk the file n+1 times.

### CODE REVIEW

**Comment by fire015** [comment]
This doesn't take into consideration if there is more than one = sign on the line.

**Comment by fire015** [comment]
Use the `getDataFromLine` method.

**Comment by urmaul** [comment]
`getDataFromLine` requires you to already know key. So we'll have to split the line anyway.

**Comment by fire015** [comment]
Ok but the code is still not right, if there is more than one = sign in the value you will only get half of the data as you are not imploding again.

**Comment by urmaul** [comment]
Third parameter of explode makes it ignore all = signs after first. [Example](http://php.net/manual/en/function.explode.php#example-4989)
Don't know why you're not using that in `getDataFromLine`.

**Comment by fire015** [comment]
Ah I didn't know that, can you update `getDataFromLine` to use this too? Can you please also test for multiple equals signs in `testGetAllReturnsAllData`. Thanks!

**Pull request merged**
