### PR TITLE
Remove Object Storage Restriction V1.10.0

### PR DESCRIPTION
**Pull request by joshualjohnson**

### CODE REVIEW

**Comment by fire015** [comment]
This wouldn't work, json decode needs to return an array (as you can see the unit tests have failed).

**Comment by joshualjohnson** [comment]
Yeah. I saw the failures, but haven't had time to look into them. I am going to look further into object storage. I believe that this database can support object storage directly. Also Compliments on the Unit Testing and Travis CI Integration! I want to do the same to my open source projects!

**Comment by fire015** [comment]
It doesn't support objects for a reason, they are hard to store ;-)

**Comment by joshualjohnson** [comment]
But I can wrap the object in an array and store it no problem. I should be able to store an object stdClass just as easily.

**Pull request closed without merging**
