### PR TITLE
Allow Object Storage

### PR DESCRIPTION
**Pull request by joshualjohnson**
See commit notes for details.

### CODE REVIEW

**Comment by fire015** [comment]
I don't understand what the issue with associative arrays is, Flintstone has always been able to support this.

**Comment by joshualjohnson** [comment]
1) Associative arrays are fine for data being stored as PHP serialized strings because PHP supports serializing and de-serializing associative arrays. But does not work well when you are trying to use a JSON storage type. JSON does not support associative arrays.
2) Database 101 says that if I store data as a certain type, I should expect to get that same type back. If I store an array of objects in the JSON storage type, I should get back an array of objects. Not an array of associative arrays.
3) PHP supports Object data types.

With that being said, I might have a really good solution to this. Move the data type checking into the DataFormatter Interface as the method, DataFormatter::isValueData(). Flintstone would run this method before it will allow you to call the store method. Then the user creating the DataFormatter has control of what types of data can be stored. I will work on that and send you another pull request.

**Comment by fire015** [comment]
I'm sorry but JSON certainly does support associative arrays, what do you think `json_encode(array('a' => 'b'))` does? I don't think Flintstone should try and support objects for multiple reasons, feel free to maintain your own fork on this.

**Comment by joshualjohnson** [comment]
Thank you Jason for considering this addition. I would encourage you to take a closer look at the json_encode and how it outputs your example 

```php 
json_encode(array('a' => 'b'))
```

is not equal to

```php 
$obj = new stdClass();
$obj->a = 'b';
json_encode($obj)
```

but still yields the same output:

```php 
{"a": "b"}
```

That is because the {} represents objects, not arrays. Again, thanks for your consideration. 

With your permission, I will create a Flintstone2 repo that will add the object storage feature and a couple more improvements. I will provide you with the credit for the original Flintstone and keep all copyrights docs in place as to not violate any copyright laws. I will adhere to the all MIT licensing agreements and requirements. Thank you for your contribution here. This is a great library and I am excited to be able to contribute to it.

**Comment by fire015** [comment]
Fair enough, good luck!

**Comment by joshualjohnson** [comment]
Thank you sir!

**Comment by anthonycl** [comment]
So let me get this straight @fire015, you're going to limit the potential of Flintstone simply because you don't want to support objects? But many developers, including myself do want them? @joshualjohnson  you should just fork this and let real developers add real world features.

**Comment by joshualjohnson** [comment]
@anthonycl Thank you for the support. Here is a link to my fork. https://github.com/jljlabs/flintstonePlus

**Comment by fire015** [comment]
@anthonycl thank you for your kind comments. My concern with allowing objects to be stored in Flintstone is that people might start trying to store classes which will not encode/decode well (especially when they extend other objects). Also the problem with @joshualjohnson code is that by removing the 2nd param from json_decode data will always be decoded into an object even if you pass a PHP associative array, which means you are not getting the exact data type back that you stored. So I don't think there is a quick fix for this, it requires careful thought and consideration which is why I did not merge this PR and suggested a seperate fork if it solves a particular issue for now.

**Pull request closed without merging**
